### ISSUE TITLE
Sword upgraded after reloading save

### ISSUE THREAD

**Issue by Valensfd37** [Z3DR/MM3D_Randomizer#67] opened 2024-03-02 10:56 UTC
Hi! I've run into an interesting situation that's not exactly game-breaking but that should still be mentioned.

During a Glitchlees run on the nightly v1.3.0-5d9cf4 I discovered my Sword upgraded from the basic Kokiri all the way to Gilded after saving and reloading.
I played this save over multiple days so it wasn't the first save and reload on this one.
I've checked the spoiler log and I definetly didn't get the remaining progressive sword drop (One being Milkbar Gorman when I didn't even get Romani's mask)
What I did was get the 100 rupees and gold dust Smithy check on the session before the sword appearing, so I believe the game might have incorrectly registered me as having the swords and updated it on a reload.

I've added the spoiler log just in case.

[323997154 (Captain's Hat, Bottled Gold Dust, Hero Shield, Bottled Hot Water, Pendant of Memories)-spoilerlog.zip](https://github.com/Z3DR/MM3D_Randomizer/files/14469002/323997154.Captain.s.Hat.Bottled.Gold.Dust.Hero.Shield.Bottled.Hot.Water.Pendant.of.Memories.-spoilerlog.zip)

**Comment by PhlexPlexico** [comment] 2024-03-02 15:10
Hey thanks for the report! Swords have been giving us a bit of grief lately. I think there's just a missing Zubora patch for the gold dust, I'll be sure to take a look into this, thanks!

**Comment by PhlexPlexico** [comment] 2024-03-02 15:42
Hmmm so I tried repeating your steps (kokiri sword, gave 100 rupees, waited a day, had gold dust, got gilded sword check and saved) and I can't seem to reproduce this. You didn't play song of time or save as a different form other than human, did you?

**Comment by Valensfd37** [comment] 2024-03-03 12:19
I streamed the whole run and from looking at the VOD, I did play song of time right before saving and quitting and the gilded sword appeared when coming out the clock tower.
I just didn't notice since I saved right after. ( I even opened the gear menu to check if I had kept Kafei's pendant during the reset and somehow didn't notice the sword V_V )

So yeah, it was on SoT reset,my bad. I do have a clip if that's helpful although I doubt it.

**Comment by PhlexPlexico** [comment] 2024-03-03 14:42
No, it's definitely helpful as there's now a way of seeing what checks you did up to song of time. That way we can narrow down and see if we can find a reproducible set of steps to narrow down where these flags are being set. Would you please send a link to the vod?
Thanks!

**Comment by Valensfd37** [comment] 2024-03-03 16:21
Oh! Gotcha, so here's the full run vods
Pt1 https://www.twitch.tv/videos/2074227073
Pt2 (Gilded sword appeared at about 4:50:30) https://www.twitch.tv/videos/2076077561
Pt3 https://www.twitch.tv/videos/2077957045

**Comment by Valensfd37** [comment] 2024-03-03 21:47
I found it! so it seems to have been getting the weird milk check (Speaking with the gorman bros after getting the request from the troupe leader) that did it.
I already had the weird milk in my inventory so that might be the reason for it.

**Comment by PhlexPlexico** [comment] 2024-03-04 15:57
Hey,

Thanks for the report! This definitely helped and I believe I found the issue. It appears that the BitField for checking some stuff in the background for the rando wasn't set correctly. Looks like this will be fixed in the next push.

Thanks!

**Comment by PhlexPlexico** [comment] 2024-03-09 01:45
Fixed in latest nightly, closing now.

**Closed by PhlexPlexico** 2024-03-09 01:45 UTC
