### ISSUE TITLE
game Crashing

### ISSUE THREAD

**Issue by Dagmear456** [Z3DR/MM3D_Randomizer#109] opened 2024-07-29 23:40 UTC
the Game keeps crashing every time i try and load a file

**Comment by PhlexPlexico** [comment] 2024-07-29 23:57
Please provide more information:

- What version of the randomizer are you using?
- What version of the game are you using?
- What platform you're playing on (3DS/Emu)?
- Please ensure the proper game Version, Region, and Platform are selected in the Game Settings menu before generating a new seed
- Have you had any other Mods installed? ie. MM3D Practice Patch or Project Restoration
- If you're using any non randomizer mods or cheats please disable them then try again to see if the issue is randomizer specific.
- The patch files (code.ips, exheader.bin, and romfs) should be the only files located in the folder /luma/titles/0004000000125500 on your SD card.
REMINDER: If you're on version 1.1 of the game it can take up to a minute for the game to launch due to the randomizer unpatching the 1.1 changes!

**Comment by Dagmear456** [comment] 2024-07-30 00:08
rando vers: 1.4.0, game Vers: 1.1, System: 3DS, and not using mods

**Comment by PhlexPlexico** [comment] 2024-07-30 00:09
Did you have project restoration installed prior to? What's the crash screen? Where does it get to for loading?

**Comment by Dagmear456** [comment] 2024-07-30 00:18
what's project Restoration
![20240729_201617](https://github.com/user-attachments/assets/bc2410cf-6ab1-4a1d-bc17-b1af162f7f47)

**Comment by PhlexPlexico** [comment] 2024-07-30 00:31
When exactly is this crashing? On launch? On save file creation?

It's crashing because it's trying to read from the save file and unable to do so. I would recommend reinstalling the game if it's a digital copy.

**Comment by Dagmear456** [comment] 2024-07-30 00:33
upon loading a File, and it's a physical copy

**Comment by PhlexPlexico** [comment] 2024-07-30 00:33
Did you create a new save when starting the randomizer?

**Comment by Dagmear456** [comment] 2024-07-30 00:34
yes i did

**Comment by PhlexPlexico** [comment] 2024-07-30 00:35
Try using an older version of the Randomizer, then? Does the last stable release work for you?

**Comment by Dagmear456** [comment] 2024-07-30 00:38
i think so, but i really want to try the new feature

**Comment by PhlexPlexico** [comment] 2024-07-30 12:50
Okay well if you wish to try the new features, I would attempt to start with sword and shield instead, and see if that fixes it. 

Thanks!

**Comment by PhlexPlexico** [comment] 2024-07-30 14:01
This should be fixed in the next nightly.

**Comment by PhlexPlexico** [comment] 2024-07-30 18:35
Latest nightly should fix this issue now.

**Closed by PhlexPlexico** 2024-07-30 18:35 UTC
